modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/matthewperiut/chiseler/issues"
license = "MIT"

[[mods]]
modId = "chiseler"
version = "${version}"
displayName = "Chiseler"
authors = "slainlight"
description = '''
Adds a machine to chisel blocks for you
'''
logoFile = "assets/chiseler/logo.png"

[[dependencies.chiseler]]
modId = "neoforge"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.chiseler]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.6,1.21.7]"
ordering = "NONE"
side = "BOTH"

[[dependencies.chiseler]]
modId="chisel"
type="required"
versionRange="[2.0.0,)"